name: Build -> Test -> Release

on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta
      - '*.x*'

env:
  HUSKY: 0

jobs:
  release:
    name: Build -> Test -> Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup LTS Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build:packages

      - name: Test
        run: yarn test:all

      - name: Release
        if: ${{ success() && (github.event_name != 'pull_request' || github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        env:
          GITHUB_TOKEN: ${{ secrets.TRRACK_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
